### CSCI561 - Fall 2014 - Sample Makefile

### Example for a C++ agent:
#agent: agent.cpp
#	g++ agent.cpp -o agent

#run: agent
#	./agent

### For Java you might use:
agent: Black_White.class
	
Black_White.class: Black_White.java
	javac Black_White.java


run: Black_White.class
	java Black_White

### For python or other non-compiled languages:
#agent:
#	
#run:
#	./agent.py